// Medical universities in DACH region
export const universities = [
  // Deutschland
  'RWTH Aachen',
  'Charité - Universitätsmedizin Berlin',
  'Ruhr-Universität Bochum',
  'Rheinische Friedrich-Wilhelms-Universität Bonn',
  'Technische Universität Dresden',
  'Heinrich-Heine-Universität Düsseldorf',
  'Friedrich-Alexander-Universität Erlangen-Nürnberg',
  'Universität Duisburg-Essen',
  'Goethe-Universität Frankfurt',
  'Albert-Ludwigs-Universität Freiburg',
  'Justus-Liebig-Universität Gießen',
  'Georg-August-Universität Göttingen',
  'Universität Greifswald',
  'Martin-Luther-Universität Halle-Wittenberg',
  'Universität Hamburg',
  'Medizinische Hochschule Hannover',
  'Ruprecht-Karls-Universität Heidelberg',
  'Universität Jena',
  'Christian-Albrechts-Universität Kiel',
  'Universität zu Köln',
  'Universität Leipzig',
  'Universität zu Lübeck',
  'Otto-von-Guericke-Universität Magdeburg',
  'Johannes Gutenberg-Universität Mainz',
  'Philipps-Universität Marburg',
  'Ludwig-Maximilians-Universität München',
  'Technische Universität München',
  'Westfälische Wilhelms-Universität Münster',
  'Universität Regensburg',
  'Universität Rostock',
  'Universität des Saarlandes',
  'Eberhard Karls Universität Tübingen',
  'Universität Ulm',
  'Julius-Maximilians-Universität Würzburg',
  'Universität Witten/Herdecke',
  'Brandenburg Medical School',
  'Universität Augsburg',
  'Universität Bielefeld',
  'Medizinische Fakultät OWL (Universität Bielefeld)',

  // Österreich
  'Medizinische Universität Wien',
  'Medizinische Universität Graz',
  'Medizinische Universität Innsbruck',
  'Paracelsus Medizinische Privatuniversität Salzburg',
  'Karl Landsteiner Privatuniversität Krems',
  'Johannes Kepler Universität Linz',
  'Sigmund Freud Privatuniversität Wien',

  // Schweiz
  'Universität Basel',
  'Universität Bern',
  'Universität Freiburg/Fribourg',
  'Universität Genf',
  'Universität Lausanne',
  'Universität Neuenburg',
  'Universität Zürich',
].sort();

// Medical specialties for doctors
export const specialties = [
  'Allgemeinmedizin',
  'Anästhesiologie',
  'Anatomie',
  'Arbeitsmedizin',
  'Augenheilkunde',
  'Biochemie',
  'Chirurgie',
  'Dermatologie und Venerologie',
  'Frauenheilkunde und Geburtshilfe',
  'Gefäßchirurgie',
  'Hals-Nasen-Ohrenheilkunde',
  'Herzchirurgie',
  'Humangenetik',
  'Hygiene und Umweltmedizin',
  'Innere Medizin',
  'Innere Medizin und Angiologie',
  'Innere Medizin und Endokrinologie und Diabetologie',
  'Innere Medizin und Gastroenterologie',
  'Innere Medizin und Hämatologie und Onkologie',
  'Innere Medizin und Kardiologie',
  'Innere Medizin und Nephrologie',
  'Innere Medizin und Pneumologie',
  'Innere Medizin und Rheumatologie',
  'Kinder- und Jugendmedizin',
  'Kinder- und Jugendpsychiatrie und -psychotherapie',
  'Kinderchirurgie',
  'Laboratoriumsmedizin',
  'Mikrobiologie, Virologie und Infektionsepidemiologie',
  'Mund-Kiefer-Gesichtschirurgie',
  'Neurochirurgie',
  'Neurologie',
  'Neuropathologie',
  'Nuklearmedizin',
  'Öffentliches Gesundheitswesen',
  'Orthopädie und Unfallchirurgie',
  'Pathologie',
  'Pharmakologie',
  'Physikalische und Rehabilitative Medizin',
  'Physiologie',
  'Plastische und Ästhetische Chirurgie',
  'Psychiatrie und Psychotherapie',
  'Psychosomatische Medizin und Psychotherapie',
  'Radiologie',
  'Rechtsmedizin',
  'Strahlentherapie',
  'Thoraxchirurgie',
  'Transfusionsmedizin',
  'Urologie',
  'Viszeralchirurgie',
  'Zahnmedizin',
].sort();
